# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false  
  config.vm.define :centos_Balancer do |server|
    server.vm.box = "centos1706_v0.2.0_rabbitmq_sensu_guestadditions"
    server.vm.network :private_network, ip: "192.168.56.103"
    server.vm.network "public_network", bridge: "eno1", ip:"192.168.131.15", netmask: "255.255.255.0"
    server.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "centos_Balancer" ]
    end
    server.vm.provision "shell", inline: <<-SHELL
 
     yum install -y wget haproxy unzip
     wget https://releases.hashicorp.com/consul-template/0.19.4/consul-template_0.19.4_linux_amd64.zip -P /tmp
     unzip /tmp/consul-template_0.19.4_linux_amd64.zip -d /tmp
     mv /tmp/consul-template /usr/bin
     mkdir /etc/consul-template

    SHELL
  end
end
